stages:
  - build

build:
  image: docker:latest
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "$CI_COMMIT_SHA" > DUBuild/versionhash
    - docker build --pull -t "registry.internal.st/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:v2" .
    - docker push "registry.internal.st/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"