stages:
  - test
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build:
  image: docker:latest
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "$CI_COMMIT_SHA" > DUBuild/versionhash
    - docker build --pull -t "$LOCAL_DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME" .
    - docker tag v3 "$LOCAL_DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    - docker push "$LOCAL_DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
  variables:
   GIT_SUBMODULE_STRATEGY: recursive
  script:
   - dotnet restore "$CI_PROJECT_DIR/DUBuild.Tests/DUBuild.Tests.csproj"
   - dotnet test "$CI_PROJECT_DIR/DUBuild.Tests/DUBuild.Tests.csproj" --logger "junit;LogFilePath=$CI_PROJECT_DIR/app/results.xml"
  artifacts:
    reports:
      junit: $CI_PROJECT_DIR/app/results.xml